### ISSUE TITLE
Target .NET Core 2.0

### ISSUE THREAD

**Issue by MikeGoldsmith** [OrleansContrib/OrleansCouchbaseProvider#20]

**Comment by dad045** [comment]
Any progress here?  I saw in another post that this was going worked on and a branch would be introduced soon.

**Comment by MikeGoldsmith** [comment]
Hi @dad045 

I did start porting the project, but got waylaid by other work. It's not as simple as updating the `FrameworkTargets` because the current project targets the older Orleans APIs and we should update to the newer versions too.

I don't think it'll be too much work, but need a head of steam to get through it.

Happy for contributions if you're wanting this sooner rather than later and have the time.

**Comment by dad045** [comment]
Hi Mike, I do need it sooner rather then later, so I've started working on it.  

How important is this ability to specify grain expiration?  IMO it isn't important and I was thinking about leaving it out.  At least for now.  Thoughts?

**Comment by MikeGoldsmith** [comment]
I don't think it's a critical feature to include at first, and can be introduced later if required.

**Comment by dad045** [comment]
I finished this a few weeks ago, but I need some time to clean it up and add some unit tests.  Please let me know if anyone needs/wants this sooner.

**Comment by MikeGoldsmith** [comment]
Hi @dad045 - I have a few cycles available to help get this reviewed / merged if it's ready.

**Comment by dad045** [comment]
I appear to be lacking permissions... or I am forgetting something.  I keep getting 403 errors.

**Comment by dad045** [comment]
The context of the above statement may not have been clear.  I am trying to create a PR or create branch and push to that.  I can do neither.

**Comment by MikeGoldsmith** [comment]
Unfortunately, you won't be able to push to this repository without write access (something I'm unable to provide).

You should be able to fork this repo, push changes to your fork then create the PR from your repo back to this one.

**Comment by dad045** [comment]
yeah, sorry.  I just figured that out.  I've never contributed to a non-work repo

**Comment by dad045** [comment]
Do a PR pointing to master or a branch?  I was thinking branch, but I would need someone to create one.

**Comment by MikeGoldsmith** [comment]
I've created branch **netcore2.0** for you to target for your PR. It's currently a copy of master, but is a good place to iterate on this work until we're ready to make it default.

**Comment by MikeGoldsmith** [comment]
Addressed with #26
