### ISSUE TITLE
Add NuGet publishing

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [OrleansContrib/OrleansCouchbaseProvider#5]
We should add the package to NuGet as well. I've never done this before but would like to do after resolving #1 #2 and #3

**Comment by marjum** [comment]
Hi @ashkan-saeedi-mazdeh, appreciate that you'd like to get the mentioned issues resolved for package release.  Would it be possible to obtain a pre-release NuGet package with the current latest commits beforehand?

Be happy to submit a PR with a nuspec file that can be used to publish the package.  [Process](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package) is pretty straightforward if you're not familiar with it.  How to publish pre-release is available [here](https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages).

**Comment by MikeGoldsmith** [comment]
Hi @marjum 

I think we could configure AppVeyor to run tests then package and publish to NuGet. I'm happy to look at doing this soon, it's fairly easy to accomplish.

**Comment by marjum** [comment]
Hi @MikeGoldsmith, even better, thanks!

**Comment by ashkan-saeedi-mazdeh** [comment]
Thanks Mike 👍
