### ISSUE TITLE
Reading grain state with references to other grains fails after silos restart

### ISSUE THREAD

**Issue by marjum** [OrleansContrib/OrleansCouchbaseProvider#6]
Assuming a grain's state includes references to other grains, the state's persistence succeeds to the configured Couchbase store, but reading the state back from the store fails with:

> Newtonsoft.Json.JsonSerializationException: Could not create an instance of type TestGrains.IStoredReferenceGrain. Type is an interface or abstract class and cannot be instantiated. Path 'StoredReferenceGrain.GrainId'

This occurs only after that the silos have been restarted, forcing grain deactivation, and prompting the Orleans runtime to read state upon grain reactivation.

**Comment by ReubenBond** [comment]
@marjum which version of Orleans are you running?

**Comment by marjum** [comment]
Hi, the same version referenced within the repo: v1.3.1.

**Comment by ReubenBond** [comment]
Thanks, @marjum. @ashkan-saeedi-mazdeh / @galvesribeiro: the issue here is that the provider is not being configured to be able to serialize GrainReferences. The fix is for the provider to configure JsonSerializerSettings and use those settings, eg here: https://github.com/OrleansContrib/OrleansCouchbaseProvider/blob/master/CouchBaseStorage/BaseJSONStorageProvider.cs#L146

Pre-configured serializer settings can be obtained using `Orleans.Serialization.OrleansJsonSerializerGetDefaultSerializerSettings()`

**Comment by marjum** [comment]
Thank you @ReubenBond.

@ashkan-saeedi-mazdeh / @galvesribeiro: I've been able to reproduce the issue consistently under an xUnit test scenario, and in alignment with @ReubenBond 's suggestion, verified a fix that applies serialization using OrleansJsonSerializer.GetDefaultSerializerSettings().

Happy to submit a pull request for you to review.

**Comment by ashkan-saeedi-mazdeh** [comment]
Thanks @ReubenBond  for answering this! I was at am will be at vacation for some days

@marjum  Yup this is right, Please send a PR and I'll review and merge, I'm no longer using this myself but if you want to be sure, Test the PubSubStore for storing stream subscriptions as well and try reading/writing subscriptions. That should work now as well.

**Comment by marjum** [comment]
Sure @ashkan-saeedi-mazdeh, could you please add me as a collaborator so that I may push up my branch?

**Comment by ashkan-saeedi-mazdeh** [comment]
@marjum  You don't need to be a collaborator. Fork the repo, do your changes and then create a pull request.
As the main contributor of the project, and according to the rules I should manage the repo. Also I might get back to it myself and CouchBase people actually might want to work on it. Previously they said, They'll do once they got time to do so.

**Comment by marjum** [comment]
@ashkan-saeedi-mazdeh sorry for any misunderstanding. I did not want to suggest taking over repo management at all.  I am just after delivering the fix to you for review and hopefully see it merged.

Will fork and submit PR as suggested.

**Comment by ashkan-saeedi-mazdeh** [comment]
@marjum  Thanks and sorry for the delay. Was at holidays with the family so it took more than expected

**Comment by marjum** [comment]
@ashkan-saeedi-mazdeh No problem, nothing better than some quality family time.
